apiVersion: v1
kind: Template
metadata:
  name: my-grafanadatasource
message: GrafanaDataSource ${DATASOURCE_CUSTOM_RESOURCE_NAME} has been created in project ${PROJECT_NAME}
parameters:
- description: Name of project
  name: PROJECT_NAME
  value: my-grafana
  required: true
- description: Name of GrafanaDataSource custom resource.
  name: GRAFANADATASOURCE_CR_NAME
  value: prometheus-grafanadatasource
  required: true
- description: Name of Datasource
  name: DATASOURCE_NAME
  value: Prometheus
  required: true
- description: Bearer Token for cluster-metrics-view ServiceAccount
  name: BEARER_TOKEN
  required: true
objects:
  - apiVersion: integreatly.org/v1alpha1
    kind: GrafanaDataSource
    metadata:
      name: ${GRAFANADATASOURCE_CR_NAME}
      namespace: ${PROJECT_NAME}
    spec:
      datasources:
        - access: proxy
          basicAuth: false
          editable: true
          isDefault: true
          jsonData:
            httpHeaderName1: 'Authorization'
            timeInterval: 5s
            tlsSkipVerify: true
          name: ${DATASOURCE_NAME}
          secureJsonData:
            httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
          type: prometheus
          url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
          withCredentials: false
      name: ${GRAFANADATASOURCE_CR_NAME}.yaml
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-datasources
      namespace: ${PROJECT_NAME}
    data:
      ${PROJECT_NAME}_${GRAFANADATASOURCE_CR_NAME}.yaml: |
        apiVersion: 1
        datasources:
        - access: proxy
          basicAuth: false
          editable: true
          isDefault: true
          jsonData:
            httpHeaderName1: 'Authorization'
            timeInterval: 5s
            tlsSkipVerify: true
          name: ${DATASOURCE_NAME}
          secureJsonData:
            httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
          type: prometheus
          url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
          withCredentials: false
     
